callbacks:
  patience: 100
  tol: 0
task:
  task_name: PreTraining
data:
  baseMVA: 100
  mask_value: 0.0
  mask_p_high: 0.8
  mask_p_low: 0.1
  normalization: HeteroDataMVANormalizer
  networks:
  - case162_ieee_dtc
  - case179_goc
  - case197_snem
  - case200_activ
  - case24_ieee_rts
  - case300_ieee
  - case39_epri
  - case60_c
  - case73_ieee_rts
  scenarios:
  - 50000
  - 50000
  - 50000
  - 50000
  - 50000
  - 50000
  - 50000
  - 50000
  - 50000
  test_ratio: 0.1
  val_ratio: 0.1
  workers: 16
model:
  attention_head: 8
  edge_dim: 10
  hidden_size: 48
  input_bus_dim: 15
  input_gen_dim: 6
  output_bus_dim: 2
  output_gen_dim: 1
  num_layers: 12
  type: GNS_heterogeneous
optimizer:
  beta1: 0.9
  beta2: 0.999
  learning_rate: 0.0005
  lr_decay: 0.7
  lr_patience: 5
seed: 0
training:
  batch_size: 16
  epochs: 200
  loss_weights:
  - 0.1
  - 0.1
  - 0.8
  losses:
  - LayeredWeightedPhysics
  - MaskedGenMSE
  - MaskedBusMSE
  loss_args:
  - base_weight: 0.5
  - {}
  - {}
  base_weight: 0.5
  accelerator: auto
  devices: auto
  strategy: auto
verbose: true
